version: "2"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    container_name: keycloak_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
