spring:
  application:
    name: api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      javax.persistence.validation.mode: auto
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
