server:
  port: 8081
  servlet:
    context-path: /api
jwt:
  secretKey: DCiBQbGc+wM3VYNcTn71tni9gr7Mz7nyqmrbSk8Hrso=
  expirationTime: 3600000  # 1 hour in milliseconds
spring:
  application:
    name: api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      javax.persistence.validation.mode: auto
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  io:
    akitect:
      enabled: true
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # Log the SQL parameters